---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: epp-metrics-role
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - epp-metrics-token
  verbs:
  - get
